create database latihan2;
use latihan2;
create table biodata (nama varchar(15), alamat Text);
desc biodata;
alter table biodata add column keterangan varchar(15) after alamat;
desc biodata;
alter table biodata add column id int(11) first;
desc biodata;
alter table biodata add column phone varchar(15) after alamat;
desc biodata;
alter table biodata modify column id char(11);
desc biodata;
alter table biodata change column phone hp varchar(20);
desc biodata;
alter table biodata add column email varchar(20) after hp;
desc biodata;
alter table biodata drop keterangan;
desc biodata;
alter table biodata rename data_mahasiswa;
desc data_mahasiswa;
alter table data_mahasiswa change id nim char(11);
desc data_mahasiswa;
alter table data_mahasiswa add primary key(nim);
desc data_mahasiswa;
alter table data_mahasiswa add unique key(email);
desc data_mahasiswa;