create database latihan1;
use latihan1;
create table siswa (nama varchar(100), alamat text);
desc siswa;
alter table siswa add column keterangan text after alamat;
desc siswa;
alter table siswa add column id int first;
desc siswa;
alter table siswa change column keterangan kelas text;
desc siswa;
alter table siswa modify column kelas varchar(10);
desc siswa;
alter table siswa drop column kelas;
desc siswa;
alter table siswa add primary key(id);
desc siswa;
alter table siswa drop primary key;
desc siswa;
alter table siswa add constraint PK_siswa primary key(id);
desc siswa;
alter table siswa drop primary key;
desc siswa;